version: 2.1

workflows:
  build-deploy:
    jobs:
      - build-deploy

jobs:
  build-deploy:
    machine:
      image: ubuntu-2004:current  # Specify a valid machine image
    steps:
      - checkout
      - run:
          name: Build and deploy
          command: |
            echo "Hello World - pipeline testing!"
