version: 2.1

workflows:
  build-deploy:
    jobs:
      - build-deploy

jobs:
  build-deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Install Maven
          command: |
            sudo apt-get update
            sudo apt-get install -y maven
      - run:
          name: Build JAR with Maven
          command: |
            mvn clean package -DskipTests
      - run:
          name: Install Heroku CLI
          command: |
            set -x
            sudo curl https://cli-assets.heroku.com/install.sh | sh
      - run:
          name: Set Heroku stack to container
          command: |
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku stack:set container -a eshop-server
      - run:
          name: Build and push Docker image to Heroku
          command: |
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:login
            docker build -t web .
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:push -a eshop-server web
      - run:
          name: Release Docker container on Heroku
          command: |
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:release -a eshop-server web
